#!/usr/bin/env ruby

#
#  mkrf_conf  --  configure Ruby-PgSQL
#

require "autorake/mkconfig"

Autorake.configure {

  extending_ruby

  if RUBY_VERSION < "1.9" then
    have_header "ruby.h"
    have_header "rubyio.h"
    have_header "st.h"
  else
    have_header "ruby/ruby.h"
    have_header "ruby/io.h"
  end

  incdir :postgres,        `pg_config --pkgincludedir`
  incdir :postgres_server, `pg_config --includedir-server`

  have_library "crypto"
  have_library "ssl"
  have_library "pq"

  have_header "postgres.h"
  have_header "libpq-fe.h"
  have_header "catalog/pg_type.h"

  have_func "rb_errinfo"
  have_func "rb_io_stdio_file"
  have_func "rb_locale_encoding"

}

